In [30]:
import pandas as pd
from sodapy import Socrata
import requests
import json
import time

In [8]:
def timer_func(func):
    def wrapper(*args, **kwargs):
        t1 = timer()
        result = func(*args, **kwargs)
        t2 = timer()
        print(f'{func.__name__}() executed in {(t2-t1):.6f}s')
        return result
    return wrapper

In [59]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
start = time.time()
client = Socrata("www.dati.lombardia.it", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(www.dati.lombardia.it,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get_all("nicp-bhqi", limit=100000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

end = time.time()
print(f'Socrata Executed in {end - start} seconds') 

results_df

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Socrata Executed in 93.98021197319031 seconds

        idsensore                     data valore stato idoperatore
0            5504  2023-01-01T00:00:00.000   42.1    VA           1
1            5504  2023-01-01T01:00:00.000   41.1    VA           1
2            5504  2023-01-01T02:00:00.000   39.7    VA           1
3            5504  2023-01-01T03:00:00.000   38.6    VA           1
4            5504  2023-01-01T04:00:00.000   36.9    VA           1
...           ...                      ...    ...   ...         ...
2982261      9930  2024-02-15T22:00:00.000  167.0    VA           1
2982262      9930  2024-02-15T23:00:00.000   99.0    VA           1
2982263      9930  2024-02-16T00:00:00.000   72.4    VA           1
2982264      9961  2024-02-14T00:00:00.000     33    VA           1
2982265      9965  2024-02-14T00:00:00.000     41    VA           1

[2982266 rows x 5 columns]

In [58]:
start = time.time()
url_json = "http://127.0.0.1:8000/api/collections/AirQualityMeasurement/items/"
query = "f=json&offset=0&limit=100000&skipGeometry=true"
url = f'{url_json}?{query}'
r = requests.get(url)
json_body = r.json()
from_json = pd.DataFrame(json_body)
end = time.time()
print(f'ARPAAPI Executed in {end - start} seconds') 

from_json

ARPAAPI Executed in 6.893828868865967 seconds

       sensor_id                 date    value      id
0           5557  2023-03-16T00:00:00  15.3000   60288
1           5557  2023-03-16T01:00:00  12.0000   60289
2           5557  2023-03-16T02:00:00  14.7000   60290
3           5557  2023-03-16T03:00:00  10.9000   60291
4           5557  2023-03-16T04:00:00  10.5000   60292
...          ...                  ...      ...     ...
99995       5619  2023-05-30T10:00:00   2.7000  160283
99996       5619  2023-05-30T11:00:00   2.5000  160284
99997       5619  2023-05-30T12:00:00   2.3000  160285
99998       5619  2023-05-30T13:00:00   2.7000  160286
99999       5619  2023-05-30T14:00:00   2.6000  160287

[100000 rows x 4 columns]

In [55]:
json_body

[{'sensor_id': 5557,
  'date': '2023-03-16T00:00:00',
  'value': '15.3000',
  'id': 60288},
 {'sensor_id': 5557,
  'date': '2023-03-16T01:00:00',
  'value': '12.0000',
  'id': 60289},
 {'sensor_id': 5557,
  'date': '2023-03-16T02:00:00',
  'value': '14.7000',
  'id': 60290},
 {'sensor_id': 5557,
  'date': '2023-03-16T03:00:00',
  'value': '10.9000',
  'id': 60291},
 {'sensor_id': 5557,
  'date': '2023-03-16T04:00:00',
  'value': '10.5000',
  'id': 60292},
 {'sensor_id': 5557,
  'date': '2023-03-16T05:00:00',
  'value': '10.4000',
  'id': 60293},
 {'sensor_id': 5557,
  'date': '2023-03-16T06:00:00',
  'value': '17.1000',
  'id': 60294},
 {'sensor_id': 5557,
  'date': '2023-03-16T07:00:00',
  'value': '39.6000',
  'id': 60295},
 {'sensor_id': 5557,
  'date': '2023-03-16T08:00:00',
  'value': '54.5000',
  'id': 60296},
 {'sensor_id': 5557,
  'date': '2023-03-16T09:00:00',
  'value': '38.6000',
  'id': 60297},
 {'sensor_id': 5557,
  'date': '2023-03-16T10:00:00',
  'value': '28.1000',
  'id': 60298},
 {'sensor_id': 5557,
  'date': '2023-03-16T11:00:00',
  'value': '23.4000',
  'id': 60299},
 {'sensor_id': 5557,
  'date': '2023-03-16T12:00:00',
  'value': '17.8000',
  'id': 60300},
 {'sensor_id': 5557,
  'date': '2023-03-16T13:00:00',
  'value': '11.5000',
  'id': 60301},
 {'sensor_id': 5557,
  'date': '2023-03-16T14:00:00',
  'value': '11.1000',
  'id': 60302},
 {'sensor_id': 5557,
  'date': '2023-03-16T15:00:00',
  'value': '10.4000',
  'id': 60303},
 {'sensor_id': 5557,
  'date': '2023-03-16T16:00:00',
  'value': '10.7000',
  'id': 60304},
 {'sensor_id': 5557,
  'date': '2023-03-16T17:00:00',
  'value': '14.3000',
  'id': 60305},
 {'sensor_id': 5557,
  'date': '2023-03-16T18:00:00',
  'value': '19.9000',
  'id': 60306},
 {'sensor_id': 5557,
  'date': '2023-03-16T19:00:00',
  'value': '42.9000',
  'id': 60307},
 {'sensor_id': 5557,
  'date': '2023-03-16T20:00:00',
  'value': '46.6000',
  'id': 60308},
 {'sensor_id': 5557,
  'date': '2023-03-16T21:00:00',
  'value': '59.8000',
  'id': 60309},
 {'sensor_id': 5557,
  'date': '2023-03-16T22:00:00',
  'value': '55.3000',
  'id': 60310},
 {'sensor_id': 5557,
  'date': '2023-03-16T23:00:00',
  'value': '56.8000',
  'id': 60311},
 {'sensor_id': 5557,
  'date': '2023-03-17T00:00:00',
  'value': '32.5000',
  'id': 60312},
 {'sensor_id': 5557,
  'date': '2023-03-17T01:00:00',
  'value': '20.9000',
  'id': 60313},
 {'sensor_id': 5557,
  'date': '2023-03-17T02:00:00',
  'value': '18.1000',
  'id': 60314},
 {'sensor_id': 5557,
  'date': '2023-03-17T03:00:00',
  'value': '19.7000',
  'id': 60315},
 {'sensor_id': 5557,
  'date': '2023-03-17T04:00:00',
  'value': '21.1000',
  'id': 60316},
 {'sensor_id': 5557,
  'date': '2023-03-17T05:00:00',
  'value': '20.4000',
  'id': 60317},
 {'sensor_id': 5557,
  'date': '2023-03-17T06:00:00',
  'value': '25.9000',
  'id': 60318},
 {'sensor_id': 5557,
  'date': '2023-03-17T07:00:00',
  'value': '39.0000',
  'id': 60319},
 {'sensor_id': 5557,
  'date': '2023-03-17T08:00:00',
  'value': '50.6000',
  'id': 60320},
 {'sensor_id': 5557,
  'date': '2023-03-17T09:00:00',
  'value': '48.3000',
  'id': 60321},
 {'sensor_id': 5557,
  'date': '2023-03-17T10:00:00',
  'value': '23.7000',
  'id': 60322},
 {'sensor_id': 5557,
  'date': '2023-03-17T11:00:00',
  'value': '19.7000',
  'id': 60323},
 {'sensor_id': 5557,
  'date': '2023-03-17T12:00:00',
  'value': '16.9000',
  'id': 60324},
 {'sensor_id': 5557,
  'date': '2023-03-17T13:00:00',
  'value': '14.9000',
  'id': 60325},
 {'sensor_id': 5557,
  'date': '2023-03-17T14:00:00',
  'value': '14.9000',
  'id': 60326},
 {'sensor_id': 5557,
  'date': '2023-03-17T15:00:00',
  'value': '15.1000',
  'id': 60327},
 {'sensor_id': 5557,
  'date': '2023-03-17T16:00:00',
  'value': '15.0000',
  'id': 60328},
 {'sensor_id': 5557,
  'date': '2023-03-17T17:00:00',
  'value': '20.6000',
  'id': 60329},
 {'sensor_id': 5557,
  'date': '2023-03-17T18:00:00',
  'value': '30.4000',
  'id': 60330},
 {'sensor_id': 5557,
  'date': '2023-03-17T19:00:00',
  'value': '45.1000',
  'id': 60331},
 {'sensor_id': 5557,
  'date': '2023-03-17T20:00:00',
  'value': '77.1000',
  'id': 60332},
 {'sensor_id': 5557,
  'date': '2023-03-17T21:00:00',
  'value': '88.0000',
  'id': 60333},
 {'sensor_id': 5557,
  'date': '2023-03-17T22:00:00',
  'value': '76.1000',
  'id': 60334},
 {'sensor_id': 5557,
  'date': '2023-03-17T23:00:00',
  'value': '75.3000',
  'id': 60335},
 {'sensor_id': 5557,
  'date': '2023-03-18T00:00:00',
  'value': '70.3000',
  'id': 60336},
 {'sensor_id': 5557,
  'date': '2023-03-18T01:00:00',
  'value': '75.4000',
  'id': 60337},
 {'sensor_id': 5557,
  'date': '2023-03-18T02:00:00',
  'value': '66.3000',
  'id': 60338},
 {'sensor_id': 5557,
  'date': '2023-03-18T03:00:00',
  'value': '65.4000',
  'id': 60339},
 {'sensor_id': 5557,
  'date': '2023-03-18T04:00:00',
  'value': '53.8000',
  'id': 60340},
 {'sensor_id': 5557,
  'date': '2023-03-18T05:00:00',
  'value': '49.1000',
  'id': 60341},
 {'sensor_id': 5557,
  'date': '2023-03-18T06:00:00',
  'value': '46.0000',
  'id': 60342},
 {'sensor_id': 5557,
  'date': '2023-03-18T07:00:00',
  'value': '50.1000',
  'id': 60343},
 {'sensor_id': 5557,
  'date': '2023-03-18T08:00:00',
  'value': '48.3000',
  'id': 60344},
 {'sensor_id': 5557,
  'date': '2023-03-18T09:00:00',
  'value': '48.3000',
  'id': 60345},
 {'sensor_id': 5557,
  'date': '2023-03-18T10:00:00',
  'value': '39.8000',
  'id': 60346},
 {'sensor_id': 5557,
  'date': '2023-03-18T11:00:00',
  'value': '33.7000',
  'id': 60347},
 {'sensor_id': 5557,
  'date': '2023-03-18T12:00:00',
  'value': '23.6000',
  'id': 60348},
 {'sensor_id': 5557,
  'date': '2023-03-18T13:00:00',
  'value': '20.1000',
  'id': 60349},
 {'sensor_id': 5557,
  'date': '2023-03-18T14:00:00',
  'value': '20.8000',
  'id': 60350},
 {'sensor_id': 5557,
  'date': '2023-03-18T15:00:00',
  'value': '14.5000',
  'id': 60351},
 {'sensor_id': 5557,
  'date': '2023-03-18T16:00:00',
  'value': '11.5000',
  'id': 60352},
 {'sensor_id': 5557,
  'date': '2023-03-18T17:00:00',
  'value': '11.1000',
  'id': 60353},
 {'sensor_id': 5557,
  'date': '2023-03-18T18:00:00',
  'value': '12.5000',
  'id': 60354},
 {'sensor_id': 5557,
  'date': '2023-03-18T19:00:00',
  'value': '24.6000',
  'id': 60355},
 {'sensor_id': 5557,
  'date': '2023-03-18T20:00:00',
  'value': '51.4000',
  'id': 60356},
 {'sensor_id': 5557,
  'date': '2023-03-18T21:00:00',
  'value': '67.2000',
  'id': 60357},
 {'sensor_id': 5557,
  'date': '2023-03-18T22:00:00',
  'value': '65.4000',
  'id': 60358},
 {'sensor_id': 5557,
  'date': '2023-03-18T23:00:00',
  'value': '65.0000',
  'id': 60359},
 {'sensor_id': 5557,
  'date': '2023-03-19T00:00:00',
  'value': '53.4000',
  'id': 60360},
 {'sensor_id': 5557,
  'date': '2023-03-19T01:00:00',
  'value': '49.3000',
  'id': 60361},
 {'sensor_id': 5557,
  'date': '2023-03-19T02:00:00',
  'value': '51.7000',
  'id': 60362},
 {'sensor_id': 5557,
  'date': '2023-03-19T03:00:00',
  'value': '58.8000',
  'id': 60363},
 {'sensor_id': 5557,
  'date': '2023-03-19T04:00:00',
  'value': '50.6000',
  'id': 60364},
 {'sensor_id': 5557,
  'date': '2023-03-19T05:00:00',
  'value': '40.9000',
  'id': 60365},
 {'sensor_id': 5557,
  'date': '2023-03-19T06:00:00',
  'value': '36.1000',
  'id': 60366},
 {'sensor_id': 5557,
  'date': '2023-03-19T07:00:00',
  'value': '38.1000',
  'id': 60367},
 {'sensor_id': 5557,
  'date': '2023-03-19T08:00:00',
  'value': '36.2000',
  'id': 60368},
 {'sensor_id': 5557,
  'date': '2023-03-19T09:00:00',
  'value': '26.1000',
  'id': 60369},
 {'sensor_id': 5557,
  'date': '2023-03-19T10:00:00',
  'value': '17.0000',
  'id': 60370},
 {'sensor_id': 5557,
  'date': '2023-03-19T11:00:00',
  'value': '16.3000',
  'id': 60371},
 {'sensor_id': 5557,
  'date': '2023-03-19T12:00:00',
  'value': '15.2000',
  'id': 60372},
 {'sensor_id': 5557,
  'date': '2023-03-19T13:00:00',
  'value': '13.1000',
  'id': 60373},
 {'sensor_id': 5557,
  'date': '2023-03-19T14:00:00',
  'value': '10.0000',
  'id': 60374},
 {'sensor_id': 5557,
  'date': '2023-03-19T15:00:00',
  'value': '11.1000',
  'id': 60375},
 {'sensor_id': 5557,
  'date': '2023-03-19T16:00:00',
  'value': '10.2000',
  'id': 60376},
 {'sensor_id': 5557,
  'date': '2023-03-19T17:00:00',
  'value': '15.2000',
  'id': 60377},
 {'sensor_id': 5557,
  'date': '2023-03-19T18:00:00',
  'value': '16.1000',
  'id': 60378},
 {'sensor_id': 5557,
  'date': '2023-03-19T19:00:00',
  'value': '18.8000',
  'id': 60379},
 {'sensor_id': 5557,
  'date': '2023-03-19T20:00:00',
  'value': '38.0000',
  'id': 60380},
 {'sensor_id': 5557,
  'date': '2023-03-19T21:00:00',
  'value': '31.4000',
  'id': 60381},
 {'sensor_id': 5557,
  'date': '2023-03-19T22:00:00',
  'value': '37.4000',
  'id': 60382},
 {'sensor_id': 5557,
  'date': '2023-03-19T23:00:00',
  'value': '38.1000',
  'id': 60383},
 {'sensor_id': 5557,
  'date': '2023-03-20T00:00:00',
  'value': '34.8000',
  'id': 60384},
 {'sensor_id': 5557,
  'date': '2023-03-20T01:00:00',
  'value': '30.7000',
  'id': 60385},
 {'sensor_id': 5557,
  'date': '2023-03-20T02:00:00',
  'value': '28.3000',
  'id': 60386},
 {'sensor_id': 5557,
  'date': '2023-03-20T03:00:00',
  'value': '24.0000',
  'id': 60387}]